### ISSUE TITLE
About "kayoyin / transformer-slt" project

### ISSUE THREAD

**Issue by yemenoglu** [hshreeshail/hshreeshail.github.io#1]
Hi, i see, you finished this project (https://github.com/kayoyin/transformer-slt) and got the result. I also trying to get result, but i took an error. Could you help me please

I done training stage, after i am trying to inference stage with "python translate.py -model model [model2 model3 ...] -src data/phoenix2014T.test.gloss -output pred.txt -gpu 0 -replace_unk -beam_size 4" comment, 
but i am taking this error;

"[2023-04-29 02:26:55,171 INFO] Translating shard 0.
Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/home/yemenoglu/anaconda3/venv/transformer-slt/onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "/home/yemenoglu/anaconda3/venv/transformer-slt/onmt/bin/translate.py", line 25, in translate
    translator.translate(
  File "/home/yemenoglu/anaconda3/venv/transformer-slt/onmt/translate/translator.py", line 351, in translate
    batch_data = self.translate_batch(
  File "/home/yemenoglu/anaconda3/venv/transformer-slt/onmt/translate/translator.py", line 546, in translate_batch
    return self._translate_batch_with_strategy(batch, src_vocabs,
  File "/home/yemenoglu/anaconda3/venv/transformer-slt/onmt/translate/translator.py", line 677, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/home/yemenoglu/anaconda3/venv/transformer-slt/onmt/translate/beam_search.py", line 190, in advance
    torch.div(self.topk_ids, vocab_size, out=self._batch_index)
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead"

Could you help me please, thank you.

**Comment by hshreeshail** [comment]
Hi,
I had also tried to run the code, but did not finish running it. Sorry
about that.
Shreeshail

**Comment by yemenoglu** [comment]
Thank you, actually i am trying to run the Continous SLR project, could you suggest any no error and explained well CSLR project that you know ?
Thank you, have a nice fay.

**Comment by hshreeshail** [comment]
I was able to run this successfully:  hulianyuyy/Temporal-Lift-Pooling:
Temporal Lift Pooling for Continuous Sign Language Recognition (ECCV2022)
(github.com) <https://github.com/hulianyuyy/Temporal-Lift-Pooling>

**Comment by yemenoglu** [comment]
Thank you son much, have a nice day.

**Comment by yemenoglu** [comment]
> I was able to run this successfully: hulianyuyy/Temporal-Lift-Pooling: Temporal Lift Pooling for Continuous Sign Language Recognition (ECCV2022) (github.com) <https://github.com/hulianyuyy/Temporal-Lift-Pooling>

Hi again,
You said i run above project, what was your Python, cuda, pytorch etc. version?
Could you write it?
Thank you.

**Comment by hshreeshail** [comment]
Hi,
My CUDA version was 10.1. Sorry, I don't have the exact details of the
environment since the VM I was working on got wiped out unexpectedly, so I
lost the environment. But as far as I remember, I had followed the
instructions in the README.md and they had worked for me.

**Comment by yemenoglu** [comment]
Ok, thanks again, i will try. Everytime, i am taking some errors. Trying again, again, it will solve, i hope.
Thanks.
